import initTabNav from './modules/tabNav.js';
import initAccordion from './modules/accordion.js';
import initscrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/scrol-animation.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimais from './modules/fetch-animais.js';

initTabNav();
initAccordion();
initscrollSuave();
initAnimacaoScroll();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
